deployer: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
rpcUrl: "http://127.0.0.1:8545"
minBaseFee: "1"
burnedFee: "1"
mods:
  - MinterMod
  - UnlimitedMinterMod
publish:
referrers:
  - address: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
    fee: "1"
